# Generated by Django 4.2 on 2024-12-14 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_chat_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="participant",
        ),
        migrations.AddField(
            model_name="chat",
            name="participant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
