# Generated by Django 4.2 on 2024-12-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_alter_chat_participant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="participant",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="chat",
            name="token",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
