# Generated by Django 4.2 on 2024-12-15 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0008_remove_chat_user_chat_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
