# Generated by Django 4.2 on 2024-12-15 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_alter_chat_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
